name: Deploy PR Preview

on:
  workflow_run:
    workflows: ["PR Preview"]
    types:
      - completed

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4